org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Mod
mod_id=ftbchunks
readable_name=FTB Chunks
mod_version=8
mod_author=FTB Team

# Maven
archives_base_name=ftb-chunks
maven_group=dev.ftb.mods

# MC
minecraft_version=26.1.2
supported_minecraft_versions=26.1,26.1.1,26.1.2
minecraft_version_range_maven=[26.1,27)
minecraft_version_range_semver=>=26.1.0

# Deps
neoforge_version=26.1.2.94
neoforge_version_range=[26.1.2.71,26.2)
neoforge_loader_version=4

fabric_loader_version=0.18.6
fabric_api_version=0.149.1+26.1.2
fabric_api_version_range=>=0.149.1+26.1.2

ftb_library_version=26.1.2.7
ftb_teams_version=26.1.2.4
ftb_backups3_version=26.1.2.1

curseforge_id_forge=314906
curseforge_id_fabric=472657

